# Generated by Django 4.2.3 on 2023-07-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who_am_I', models.CharField(max_length=100)),
                ('short_story', models.TextField()),
                ('video', models.FileField(upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_unusual_events', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.FileField(upload_to='event')),
            ],
        ),
        migrations.CreateModel(
            name='My_life',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='my_life')),
                ('my_story_title', models.CharField(max_length=50)),
                ('my_story', models.TextField()),
                ('second_img', models.FileField(upload_to='my_life')),
                ('my_second_story_title', models.CharField(max_length=50)),
                ('my_second_story', models.TextField()),
            ],
        ),
    ]
