# Generated by Django 4.2.3 on 2023-07-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_achchivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='my_achchivments')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='My_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfoli_descriptions', models.CharField(max_length=250)),
                ('img1', models.FileField(upload_to='portfolio')),
                ('img2', models.FileField(upload_to='portfolio')),
                ('img3', models.FileField(blank=True, null=True, upload_to='portfolio')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('client', models.CharField(max_length=30)),
                ('project_finishing_date', models.DateField()),
                ('project_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='My_status_for_future',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('img', models.FileField(upload_to='mission')),
            ],
        ),
        migrations.CreateModel(
            name='Surprising_situations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='surprising_situation')),
                ('title', models.CharField(max_length=30)),
                ('interesting_emotion', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
