# Generated by Django 4.2.3 on 2023-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_my_achchivements_my_portfolio_my_status_for_future_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='my_pictures')),
                ('img2', models.FileField(blank=True, null=True, upload_to='my_pictures')),
                ('img3', models.FileField(blank=True, null=True, upload_to='my_pictures')),
                ('img4', models.FileField(blank=True, null=True, upload_to='my_pictures')),
                ('img5', models.FileField(blank=True, null=True, upload_to='my_pictures')),
            ],
        ),
    ]
