# Generated by Django 4.2.3 on 2023-07-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_remove_my_images_img2_remove_my_images_img3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_images',
            name='img2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='my_pictures'),
        ),
        migrations.AddField(
            model_name='my_images',
            name='img3',
            field=models.FileField(blank=True, default=None, null=True, upload_to='my_pictures'),
        ),
        migrations.AddField(
            model_name='my_images',
            name='img4',
            field=models.FileField(blank=True, default=None, null=True, upload_to='my_pictures'),
        ),
        migrations.AddField(
            model_name='my_images',
            name='img5',
            field=models.FileField(blank=True, default=None, null=True, upload_to='my_pictures'),
        ),
    ]
