# Generated by Django 4.2.3 on 2023-07-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_my_images_img2_my_images_img3_my_images_img4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_images',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='my_images',
            name='img3',
        ),
        migrations.RemoveField(
            model_name='my_images',
            name='img4',
        ),
        migrations.RemoveField(
            model_name='my_images',
            name='img5',
        ),
    ]
