# Generated by Django 4.2.3 on 2023-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img',
            field=models.FileField(blank=True, default=None, null=True, upload_to='blog-img'),
        ),
    ]
